name = "gyuanpalace"
main = "worker.js"
compatibility_date = "2025-01-01"
account_id = "ad75e8e45b6eeea0b0d6f7c97aeb83be"

[vars]
CHAIN_NAME = "GyuanPalace"
PROTOCOL = "MemoryChain/1.0"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "gyuanpalace_db"
database_name = "gyuanpalace-db"
database_id = "6cfddbd9-eaf5-4220-bfe7-4005e53aa677"