export const ENDPOINTS = {
  palace: {
    status: { path: '/api/palace/status', method: 'GET', cache: true },
    blocks: { path: '/api/palace/blocks', method: 'GET' },
    trades: { path: '/api/palace/trades', method: 'GET' },
    rooms: { path: '/api/rooms/status', method: 'GET' },
    command: { path: '/api/palace/command', method: 'POST' },
    store: { path: '/api/palace/store', method: 'POST' },
    trade: { path: '/api/palace/trade', method: 'POST' },
  },
  system: {
    stats: { path: '/api/system/stats', method: 'GET' },
    pool: { path: '/api/system/pool', method: 'GET' },
  },
  wallet: {
    register: { path: '/api/wallet/register', method: 'POST' },
    info: { path: '/api/wallet/info', method: 'GET' },
    keys: { path: '/api/wallet/keys', method: 'GET', admin: true },
    profile: { path: '/api/wallet/profile', method: 'GET' },
    rotateKey: { path: '/api/wallet/rotate-key', method: 'POST', admin: true },
  },
  agent: {
    list: { path: '/api/agent/list', method: 'GET' },
    whoami: { path: '/api/agent/whoami', method: 'GET' },
    describe: { path: '/api/agent/describe', method: 'GET' },
    bind: { path: '/api/agent/bind', method: 'POST' },
    nodeList: { path: '/api/node/list', method: 'GET' },
    clones: { path: '/api/clones', method: 'GET' },
    cloneStatus: { path: '/api/clone/status', method: 'GET' },
    cloneRecover: { path: '/api/clone/recover', method: 'GET' },
    cloneIsolate: { path: '/api/clone/isolate', method: 'POST' },
    cloneQuarantine: { path: '/api/clone/quarantine', method: 'POST' },
  },
  task: {
    active: { path: '/api/tasks/active', method: 'GET', cache: true },
    create: { path: '/api/task/create', method: 'POST' },
    claim: { path: '/api/task/claim', method: 'POST' },
    complete: { path: '/api/task/complete', method: 'POST' },
    remove: { path: '/api/task/delete', method: 'POST' },
    clearAll: { path: '/api/task/clear-all', method: 'POST' },
  },
  memory: {
    list: { path: '/api/memory/list', method: 'GET' },
    detail: { path: '/api/memory/detail', method: 'GET' },
    create: { path: '/api/memory/create', method: 'POST' },
    remove: { path: '/api/memory/delete', method: 'POST' },
    search: { path: '/api/memory/search', method: 'GET' },
    export: { path: '/api/memory/export', method: 'GET' },
  },
  graph: {
    status: { path: '/api/graph/status', method: 'GET' },
    nodes: { path: '/api/graph/nodes', method: 'GET' },
    semantic: { path: '/api/semantic/status', method: 'GET' },
  },
  pool: {
    status: { path: '/api/pool/status', method: 'GET' },
    expand: { path: '/api/pool/expand', method: 'POST' },
    airdrop: { path: '/api/pool/airdrop', method: 'POST', admin: true },
    decay: { path: '/api/pool/decay', method: 'POST', admin: true },
  },
  audit: {
    list: { path: '/api/audit/list', method: 'GET' },
    commands: { path: '/api/command/list', method: 'GET' },
  },
  mining: {
    status: { path: '/api/mining/status', method: 'GET' },
    background: { path: '/api/mining/background', method: 'GET' },
    config: { path: '/api/mining/config', method: 'GET' },
    setConfig: { path: '/api/mining/config', method: 'POST' },
    start: { path: '/api/mining/start', method: 'POST' },
    trigger: { path: '/api/mining/trigger', method: 'POST' },
    sync: { path: '/api/mining/sync', method: 'POST' },
    stats: { path: '/api/mining/stats', method: 'GET' },
  },
  broadcast: {
    schedule: { path: '/api/broadcast/schedule', method: 'GET' },
    create: { path: '/api/broadcast/schedule', method: 'POST' },
    update: { path: '/api/broadcast/schedule/update', method: 'POST' },
    remove: { path: '/api/broadcast/schedule/delete', method: 'POST' },
    wake: { path: '/api/broadcast/wake', method: 'POST' },
  },
  workflow: {
    list: { path: '/api/workflow/list', method: 'GET' },
    publish: { path: '/api/workflow/publish', method: 'POST' },
    claim: { path: '/api/workflow/claim', method: 'POST' },
    execute: { path: '/api/workflow/execute', method: 'POST' },
    complete: { path: '/api/workflow/complete', method: 'POST' },
  },
  debt: {
    list: { path: '/api/debt/list', method: 'GET' },
    issue: { path: '/api/debt/issue', method: 'POST' },
    repay: { path: '/api/debt/repay', method: 'POST' },
  },
  governance: {
    bugs: { path: '/api/bug/list', method: 'GET' },
    bugReport: { path: '/api/bug/report', method: 'POST' },
    bugConfirm: { path: '/api/bug/confirm', method: 'POST' },
    bugFix: { path: '/api/bug/fix', method: 'POST' },
    proposals: { path: '/api/proposal/list', method: 'GET' },
    proposalCreate: { path: '/api/proposal/create', method: 'POST' },
    proposalVote: { path: '/api/proposal/vote', method: 'POST' },
    proposalExecute: { path: '/api/proposal/execute', method: 'POST' },
  },
  heatmap: {
    status: { path: '/api/heatmap/status', method: 'GET' },
    tool: { path: '/api/heatmap/tool', method: 'GET' },
    node: { path: '/api/heatmap/node', method: 'GET' },
    conversation: { path: '/api/heatmap/conversation', method: 'GET' },
    memory: { path: '/api/heatmap/memory', method: 'GET' },
    realtime: { path: '/api/heatmap/realtime', method: 'GET' },
    collect: { path: '/api/heatmap/collect', method: 'POST' },
  },
  dialog: {
    cache: { path: '/api/dialog/cache', method: 'GET' },
    prepare: { path: '/api/dialog/prepare', method: 'POST' },
    record: { path: '/api/dialog/record', method: 'POST' },
    feedback: { path: '/api/dialog/feedback', method: 'POST' },
    analyze: { path: '/api/dialog/analyze', method: 'POST' },
    optimize: { path: '/api/dialog/optimize', method: 'POST' },
  },
  tools: {
    library: { path: '/api/tools/library', method: 'GET' },
    agentTools: { path: '/api/tools/agent-tools', method: 'GET' },
    stats: { path: '/api/tools/stats', method: 'GET' },
    preference: { path: '/api/tools/preference', method: 'GET' },
    callLog: { path: '/api/tools/call/log', method: 'POST' },
    initSecurity: { path: '/api/tools/init-security', method: 'POST' },
  },
  chinese: {
    stats: { path: '/api/chinese/stats', method: 'GET' },
    elementsCycle: { path: '/api/chinese/five-elements-cycle', method: 'GET' },
    fiveElements: { path: '/api/chinese/five-elements', method: 'GET' },
    solarTerms: { path: '/api/chinese/solar-terms', method: 'GET' },
    seasons: { path: '/api/chinese/seasons', method: 'GET' },
    stemsBranches: { path: '/api/chinese/stems-branches', method: 'GET' },
    tones: { path: '/api/chinese/tones', method: 'GET' },
    idioms: { path: '/api/chinese/idioms', method: 'GET' },
  },
} as const;

export const ADMIN_PATHS: ReadonlySet<string> = new Set([
  '/api/wallet/keys',
  '/api/wallet/rotate-key',
  '/api/pool/airdrop',
  '/api/pool/decay',
]);
