import { lazy } from 'react';

export const PalacePage = lazy(() => import('../../domains/palace/pages/PalacePage').then((m) => ({ default: m.PalacePage })));
export const SystemPage = lazy(() => import('../../domains/system/pages/SystemPage').then((m) => ({ default: m.SystemPage })));
export const WalletPage = lazy(() => import('../../domains/wallet/pages/WalletPage').then((m) => ({ default: m.WalletPage })));
export const AgentPage = lazy(() => import('../../domains/agent/pages/AgentPage').then((m) => ({ default: m.AgentPage })));
export const TaskPage = lazy(() => import('../../domains/task/pages/TaskPage').then((m) => ({ default: m.TaskPage })));
export const MemoryPage = lazy(() => import('../../domains/memory/pages/MemoryPage').then((m) => ({ default: m.MemoryPage })));
export const GraphPage = lazy(() => import('../../domains/graph/pages/GraphPage').then((m) => ({ default: m.GraphPage })));
export const PoolPage = lazy(() => import('../../domains/pool/pages/PoolPage').then((m) => ({ default: m.PoolPage })));
export const AuditPage = lazy(() => import('../../domains/audit/pages/AuditPage').then((m) => ({ default: m.AuditPage })));
export const MiningPage = lazy(() => import('../../domains/mining/pages/MiningPage').then((m) => ({ default: m.MiningPage })));
export const BroadcastPage = lazy(() => import('../../domains/broadcast/pages/BroadcastPage').then((m) => ({ default: m.BroadcastPage })));
export const WorkflowPage = lazy(() => import('../../domains/workflow/pages/WorkflowPage').then((m) => ({ default: m.WorkflowPage })));
export const DebtPage = lazy(() => import('../../domains/debt/pages/DebtPage').then((m) => ({ default: m.DebtPage })));
export const GovernancePage = lazy(() => import('../../domains/governance/pages/GovernancePage').then((m) => ({ default: m.GovernancePage })));
export const HeatmapPage = lazy(() => import('../../domains/heatmap/pages/HeatmapPage').then((m) => ({ default: m.HeatmapPage })));
export const DialogPage = lazy(() => import('../../domains/dialog/pages/DialogPage').then((m) => ({ default: m.DialogPage })));
export const ToolsPage = lazy(() => import('../../domains/tools/pages/ToolsPage').then((m) => ({ default: m.ToolsPage })));
export const ChinesePage = lazy(() => import('../../domains/chinese/pages/ChinesePage').then((m) => ({ default: m.ChinesePage })));
